[package]
name = "microsim"
version = "0.1.0"
edition = "2024"
default-run = "microsim"

[dependencies]
tonic-prost = "0.14"
tonic = "0.14.0"
prost = "0.14.0"
prost-types = "0.14.0"
tokio = { version = "1.43.1", features = ["rt", "macros"] }
tokio-stream = "0.1.15"
tulisp = { version = "0.27.0", features = ["etags"] }
notify = "6.1.1"
futures = "0.3.30"
log = "0.4.22"
simplelog = "0.12.2"
rand = "0.9.3"
chrono = "0.4.42"

[build-dependencies]
tonic-prost-build = { version = "0.14", features = ["cleanup-markdown"] }

[lib]
name = "microsim"
path = "src/lib.rs"
